Repository flow-build/engine, pull requests merged in 2022-11, with the labels that each got.

#139 fix: fix preProcessing on trigger finish node
  src/core/workflow/nodes/triggerFinish.js
Labels: bug, js

#141 fix(packages): :memo: update deps
  package-lock.json
  package.json
Labels: bug, dependencies, configuration

#144 Fix/timer transaction
  docker-compose.yml
  scripts/run_tests.sh
  src/core/workflow/nodes/tests/startProcessNode.test.js
  src/core/workflow/process.js
  src/core/workflow/timer.js
  src/engine/tests/integration/engine_processes.test.js
  src/engine/tests/unitary/engine.test.js
Labels: bug, configuration, js, test

#145 chore(release): 2.16.3-alpha.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#146 Fix/timer transaction
  src/core/persist/knex.js
  src/core/workflow/activity_manager.js
  src/core/workflow/process.js
  src/core/workflow/process_manager.js
  src/engine/tests/integration/engine_processes.test.js
Labels: bug, js, test

#147 chore(release): 2.16.3-alpha.2
  package-lock.json
  package.json
Labels: dependencies, configuration

#143 Fix/timer/merge develop
  src/core/persist/knex.js
  src/core/workflow/activity_manager.js
  src/core/workflow/process.js
  src/core/workflow/process_manager.js
  src/core/workflow/timer.js
  src/engine/tests/integration/engine_processes.test.js
Labels: bug, configuration, js, test

#150 Fix/event transaction
  src/core/persist/knex/process.js
  src/core/persist/knex/workflow.js
  src/core/workflow/process.js
  src/core/workflow/process_manager.js
  src/core/workflow/target.js
  src/core/workflow/workflow.js
Labels: bug, js

#151 feat: adjust timer to be 'soft deleted'
  src/core/workflow/tests/unitary/process.test.js
  src/core/workflow/tests/unitary/timer.test.js
  src/core/workflow/timer.js
Labels: feature, js, test

#153 Feat/flow 26/signal node
  README.md
Labels: feature, doc

#154 chore(release): 2.17.0-beta.3
  package-lock.json
  package.json
Labels: dependencies, configuration

#157 chore(release): 2.17.0-beta.4
  package-lock.json
  package.json
Labels: dependencies, configuration

#155 Fix/event transaction
  src/core/persist/knex/process.js
  src/core/persist/knex/workflow.js
  src/core/workflow/process.js
  src/core/workflow/process_manager.js
  src/core/workflow/target.js
  src/core/workflow/workflow.js
Labels: bug, dependencies, configuration, github-actions, doc, js, test

#159 chore(release): 2.17.0-beta.5
  package-lock.json
  package.json
Labels: dependencies, configuration

#160 Fix/timer transaction
  .github/workflows/first-time-contrib.yml
  src/core/persist/knex.js
Labels: bug, github-actions, js

#161 chore(release): 2.16.4
  package-lock.json
  package.json
Labels: dependencies, configuration

#163 fix(process): :bug: fix a duplicated return after the merges
  db/migrations/20211202133900_set_activity_manager_id_index_to_activity.js
  src/core/workflow/process.js
Labels: bug, js

#164 chore(release): 2.17.0-beta.6
  package-lock.json
  package.json
Labels: dependencies, configuration

#158 Feat/http node logs
  src/core/utils/eventEmitter.js
  src/core/workflow/nodes/http.js
Labels: feature, js

#165 Feat/http node logs
  src/core/utils/eventEmitter.js
  src/core/workflow/nodes/http.js
Labels: feature, js

#166 chore(release): 2.17.0-beta.7
  package-lock.json
  package.json
Labels: dependencies, configuration

#167 chore(release): 2.17.0
  package-lock.json
  package.json
Labels: dependencies, configuration
