Repository flow-build/engine, pull requests merged in 2022-09, with the labels that each got.

#116 chore(release): 2.13.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#115 Flow 6 notify parent on abort
  src/core/workflow/nodes/subProcess.js
  src/core/workflow/process_manager.js
  src/core/workflow/tests/examples/twoUserTasks.js
  src/engine/tests/unitary/engine.test.js
Labels: js, test

#117 chore(release): 2.14.0
  package-lock.json
  package.json
Labels: dependencies, configuration

#118 Feature/get types categories
  index.js
  src/core/utils/node_factory.js
  src/core/utils/tests/unitary/node_factory.test.js
Labels: feature, js, test

#119 chore(release): 2.15.0
  package-lock.json
  package.json
Labels: dependencies, configuration

#122 Flow 13 change node validation
  package-lock.json
  package.json
  src/cockpit/tests/unitary/cockpit.test.js
  src/core/utils/tests/unitary/node_factory.test.js
  src/core/utils/tests/unitary/nodefy.test.js
  src/core/workflow/nodes/abortProcess.js
  src/core/workflow/nodes/examples/custom.js
  src/core/workflow/nodes/examples/finish.js
  src/core/workflow/nodes/examples/flow.js
  src/core/workflow/nodes/examples/http.js
  src/core/workflow/nodes/examples/index.js
  src/core/workflow/nodes/examples/nodes.js
  src/core/workflow/nodes/examples/parameterized.js
  src/core/workflow/nodes/examples/scriptTask.js
  src/core/workflow/nodes/examples/start.js
  src/core/workflow/nodes/examples/startProcess.js
  src/core/workflow/nodes/examples/systemTask.js
  src/core/workflow/nodes/examples/timer.js
  src/core/workflow/nodes/examples/userTask.js
  src/core/workflow/nodes/finish.js
  src/core/workflow/nodes/flow.js
  src/core/workflow/nodes/formRequest.js
  src/core/workflow/nodes/http.js
  src/core/workflow/nodes/node.js
  src/core/workflow/nodes/parameterized.js
  src/core/workflow/nodes/scriptTask.js
  src/core/workflow/nodes/start.js
  src/core/workflow/nodes/startProcess.js
  src/core/workflow/nodes/subProcess.js
  src/core/workflow/nodes/systemTask.js
  src/core/workflow/nodes/tests/finishNode.test.js
  src/core/workflow/nodes/tests/flowNode.test.js
  src/core/workflow/nodes/tests/formRequestNode.test.js
  src/core/workflow/nodes/tests/httpNode.test.js
  src/core/workflow/nodes/tests/node.test.js
  src/core/workflow/nodes/tests/parameterizedNode.test.js
  src/core/workflow/nodes/tests/startNode.test.js
  src/core/workflow/nodes/tests/startProcessNode.test.js
  src/core/workflow/nodes/tests/subProcessNode.test.js
  src/core/workflow/nodes/tests/systemTaskNode.test.js
  src/core/workflow/nodes/tests/timerNode.test.js
  src/core/workflow/nodes/tests/userTaskNode.test.js
  src/core/workflow/nodes/timer.js
  src/core/workflow/nodes/userTask.js
  src/core/workflow/tests/unitary/node.test.js
  src/core/workflow/tests/unitary/node_samples.js
  src/core/workflow/tests/unitary/process.test.js
  src/engine/tests/unitary/engine.test.js
  src/engine/tests/utils/extra_nodes.js
Labels: dependencies, configuration, js, test

#123 chore(release): 2.16.0
  package-lock.json
  package.json
Labels: dependencies, configuration

#126 124 fix submissão de activity quando o activity schema é um objeto vazio
  package-lock.json
  package.json
  src/core/utils/ajvValidator.js
  src/core/utils/tests/unitary/ajvValidator.test.js
  src/core/workflow/nodes/startProcess.js
  src/core/workflow/nodes/tests/startProcessNode.test.js
  src/engine/tests/integration/engine_processes.test.js
Labels: dependencies, configuration, js, test

#127 chore(release): 2.16.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#128 fix: change condition from workflow to workflow id
  src/core/workflow/nodes/startProcess.js
Labels: bug, js

#129 chore(release): 2.16.2
  package-lock.json
  package.json
Labels: dependencies, configuration
