Repository flow-build/engine, pull requests merged in 2023-03, with the labels that each got.

#248 Sync beta with updates in master
  CHANGELOG.md
  package-lock.json
  package.json
  src/core/utils/environment.js
  src/core/utils/eventEmitter.js
  src/engine/engine.js
Labels: dependencies, configuration, feature, doc, js

#249 Hotfix: Add vm2 as dependency
  package-lock.json
  package.json
Labels: dependencies, configuration

#250 chore(release): 2.21.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#253 Add dueDate and duration to timerNode
  package-lock.json
  package.json
  src/core/workflow/nodes/examples/timer.js
  src/core/workflow/nodes/tests/timerNode.test.js
  src/core/workflow/nodes/timer.js
  src/engine/tests/unitary/engine.test.js
Labels: dependencies, configuration, feature, js, test

#255 chore(release): 2.22.0
  package-lock.json
  package.json
Labels: dependencies, configuration

#251 fix: adjust subprocess node in case workflow doesnt exist
  src/core/workflow/nodes/subProcess.js
  src/core/workflow/process.js
  src/core/workflow/process_manager.js
  src/engine/tests/integration/engine_processes.test.js
Labels: bug, js, test

#256 chore(release): 2.22.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#252 fix: adjust condition to initialize new timer on AM saving
  src/core/workflow/activity_manager.js
Labels: bug, js

#258 chore(release): 2.22.2
  package-lock.json
  package.json
Labels: dependencies, configuration

#257 Feature/flow 56 add timer job usertask
  .env.docker
  .github/workflows/pr-validation.yml
  __mocks__/bullmq/index.js
  docker-compose.yml
  package.json
  src/core/persist/knex/activityManager.js
  src/core/persist/knex/timer.js
  src/core/workflow/activity_manager.js
  src/core/workflow/events/base.js
  src/core/workflow/events/tests/events.test.js
  src/core/workflow/events/tests/examples/eventObjects.js
  src/core/workflow/events/timerEventResolver.js
  src/core/workflow/nodes/examples/userTask.js
  src/core/workflow/nodes/tests/finishNode.test.js
  src/core/workflow/nodes/tests/userTaskNode.test.js
  src/core/workflow/nodes/timer.js
  src/core/workflow/nodes/userTask.js
  src/core/workflow/tests/examples/activityManager.js
  src/core/workflow/tests/unitary/activity_manager.test.js
  src/core/workflow/tests/unitary/timer.test.js
  src/core/workflow/timer.js
  src/engine/engine.js
  src/engine/tests/unitary/engine.test.js
Labels: dependencies, configuration, feature, github-actions, js, test

#259 chore(release): 2.23.0
  package-lock.json
  package.json
Labels: dependencies, configuration

#260 Fix Timer Events UserTask Compatibility
  __mocks__/bullmq/index.js
  docker-compose.yml
  src/core/workflow/activity_manager.js
  src/core/workflow/events/base.js
  src/core/workflow/events/tests/events.test.js
  src/core/workflow/events/tests/examples/eventObjects.js
  src/core/workflow/events/timerEventResolver.js
  src/core/workflow/nodes/tests/userTaskNode.test.js
  src/core/workflow/nodes/userTask.js
  src/core/workflow/tests/examples/activityManager.js
  src/core/workflow/tests/unitary/activity_manager.test.js
Labels: bug, configuration, js, test

#261 chore(release): 2.23.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#262 Timer Management Methods
  settings/settings.js
  src/cockpit/cockpit.js
  src/cockpit/tests/unitary/cockpit.test.js
  src/cockpit/tests/unitary/cockpitUtils.js
  src/core/persist/knex/timer.js
  src/core/utils/tests/unitary/activity_manager_factory.test.js
  src/core/workflow/activity_manager.js
  src/core/workflow/nodes/http.js
  src/core/workflow/nodes/start.js
  src/core/workflow/nodes/tests/startNode.test.js
  src/core/workflow/nodes/tests/timerNode.test.js
  src/core/workflow/nodes/timer.js
  src/core/workflow/process.js
  src/core/workflow/tests/examples/activityManager.js
  src/core/workflow/tests/unitary/activity_manager.test.js
  src/core/workflow/tests/unitary/timer.test.js
  src/core/workflow/timer.js
  src/engine/engine.js
  src/engine/tests/integration/engine_processes.test.js
Labels: feature, js, test

#263 chore(release): 2.24.0
  package-lock.json
  package.json
Labels: dependencies, configuration

#264 Fix/flow 69 fix due date conversion
  src/core/workflow/activity_manager.js
  src/core/workflow/events/base.js
Labels: bug, js

#265 chore(release): 2.24.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#266 Handle no TIMER_QUEUE
  src/core/workflow/activity_manager.js
  src/core/workflow/events/timerEventResolver.js
Labels: bug, js

#267 chore(release): 2.24.2
  package-lock.json
  package.json
Labels: dependencies, configuration

#268 fix: adjust timer job payload
  src/core/workflow/activity_manager.js
  src/core/workflow/events/timerEventResolver.js
  src/core/workflow/nodes/http.js
  src/core/workflow/nodes/start.js
  src/core/workflow/nodes/timer.js
Labels: bug, js

#271 chore(release): 2.24.4
  package-lock.json
  package.json
Labels: dependencies, configuration

#272 Fix/continue process step number
  src/core/workflow/process.js
  src/engine/tests/unitary/engine.test.js
Labels: bug, js, test
