Repository flow-build/engine, pull requests merged in 2023-01, with the labels that each got.

#180 Feat/add extra_fields
  db/migrations/20221228143526_create-extra_fields-table.js
  package.json
  src/core/persist/knex.js
  src/core/persist/knex/process.js
  src/core/persist/knex/workflow.js
  src/core/persist/provider.js
  src/core/workflow/activity.js
  src/core/workflow/activity_manager.js
  src/core/workflow/base.js
  src/core/workflow/extra_fields.js
  src/core/workflow/nodes/userTask.js
  src/core/workflow/process.js
  src/core/workflow/tests/unitary/extra_fields.test.js
  src/core/workflow/tests/unitary/workflow.test.js
  src/core/workflow/workflow.js
  src/engine/tests/unitary/activity.test.js
Labels: dependencies, configuration, feature, js, test

#182 Feat/fieldlink adaptor
  index.js
  package.json
  src/cockpit/cockpit.js
  src/core/utils/node_factory.js
  src/core/utils/tests/unitary/node_factory.test.js
  src/core/workflow/lanes.js
  src/core/workflow/process.js
  src/core/workflow/tests/unitary/process.test.js
  src/engine/engine.js
  src/engine/tests/integration/engine_processes.test.js
Labels: dependencies, configuration, feature, js, test

#181 chore(release): 2.18.0-alpha.2
  package-lock.json
  package.json
Labels: dependencies, configuration

#183 chore(release): 2.18.0-alpha.3
  package-lock.json
  package.json
Labels: dependencies, configuration

#184 Feat/fieldlink adaptor
  db/migrations/20221228143526_create-extra_fields-table.js
  src/core/persist/knex.js
  src/core/persist/knex/workflow.js
  src/core/workflow/activity.js
  src/core/workflow/activity_manager.js
  src/core/workflow/process.js
  src/core/workflow/timer.js
  src/engine/engine.js
Labels: feature, js

#185 chore(release): 2.18.0-alpha.4
  package-lock.json
  package.json
Labels: dependencies, configuration

#187 feat: change extra_fields to not be nested on extra_fields
  src/core/workflow/process.js
  src/core/workflow/process_state.js
  src/core/workflow/tests/unitary/extra_fields.test.js
Labels: feature, js, test

#188 chore(release): 2.18.0-alpha.5
  package-lock.json
  package.json
Labels: dependencies, configuration

#186 Feat/flow 38
  db/migrations/20221209134026_create_switch_table.js
  src/core/persist/knex.js
  src/core/persist/provider.js
  src/core/workflow/process.js
  src/core/workflow/process_manager.js
  src/core/workflow/switch.js
  src/core/workflow/tests/unitary/process.test.js
  src/engine/engine.js
Labels: feature, js, test

#190 chore(release): 2.18.0-beta.3
  package-lock.json
  package.json
Labels: dependencies, configuration

#192 chore(release): 2.18.0-beta.4
  package-lock.json
  package.json
Labels: dependencies, configuration

#194 chore(release): 2.18.0-alpha.6
  package-lock.json
  package.json
Labels: dependencies, configuration

#195 Feat/fieldlink adaptor
  package-lock.json
  package.json
  src/core/utils/envs.js
  src/core/utils/nodefy.js
  src/core/utils/tests/unitary/nodefy.test.js
  src/core/workflow/blueprint.js
Labels: dependencies, configuration, feature, js, test

#196 chore(release): 2.18.0-alpha.7
  package-lock.json
  package.json
Labels: dependencies, configuration

#198 Fix/timer/merge beta
  package-lock.json
  src/core/persist/knex.js
  src/core/workflow/activity_manager.js
Labels: bug, configuration, js

#199 chore(release): 2.19.0-beta.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#202 fix: adjust target_process_id reference to use specified on BP
  src/core/workflow/process.js
Labels: bug, js

#203 chore(release): 2.19.0-beta.2
  package-lock.json
  package.json
Labels: dependencies, configuration

#204 Feat/fieldlink adaptor
  .github/workflows/pr-validation.yml
  .github/workflows/release-auto-pr.yml
  CHANGELOG.md
  __mocks__/axios/index.js
  db/migrations/20211202133900_set_activity_manager_id_index_to_activity.js
  db/migrations/20221018153215_create_trigger_table.js
  db/migrations/20221020185714_create_target_table.js
  db/migrations/20221025130847_create_trigger_target_table.js
  db/migrations/20221027150416_add_process_id_foreign_relation.js
  db/migrations/20221028195517_add_target_process_id_column_to_trigger.js
  db/migrations/20221028195535_add_process_state_id_column_to_target.js
  db/migrations/20221209134026_create_switch_table.js
  package-lock.json
  package.json
  src/cockpit/cockpit.js
  src/core/persist/knex.js
  src/core/persist/knex/process.js
  src/core/persist/knex/workflow.js
  src/core/persist/provider.js
  src/core/utils/node_factory.js
  src/core/utils/tests/unitary/node_factory.test.js
  src/core/workflow/activity_manager.js
  src/core/workflow/nodes/event.js
  src/core/workflow/nodes/examples/triggerFinish.js
  src/core/workflow/nodes/http.js
  src/core/workflow/nodes/index.js
  src/core/workflow/nodes/signalUserTask.js
  src/core/workflow/nodes/start.js
  src/core/workflow/nodes/targetStart.js
  src/core/workflow/nodes/tests/httpNode.test.js
  src/core/workflow/nodes/tests/targetStartNode.test.js
  src/core/workflow/nodes/tests/triggerFinishNode.test.js
  src/core/workflow/nodes/triggerFinish.js
  src/core/workflow/process.js
  src/core/workflow/process_manager.js
  src/core/workflow/switch.js
  src/core/workflow/target.js
  src/core/workflow/tests/examples/httpRetries.js
  src/core/workflow/tests/examples/targetStart.js
  src/core/workflow/tests/examples/triggerFinish.js
  src/core/workflow/tests/unitary/blueprint_samples.js
  src/core/workflow/tests/unitary/extra_fields.test.js
  src/core/workflow/tests/unitary/process.test.js
  src/core/workflow/tests/unitary/target.test.js
  src/core/workflow/tests/unitary/trigger.test.js
  src/core/workflow/trigger.js
  src/core/workflow/workflow.js
  src/engine/engine.js
  src/engine/tests/integration/engine_processes.test.js
Labels: dependencies, configuration, feature, github-actions, doc, js, test

#205 chore(release): 2.19.0-alpha.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#206 chore: update lib version
  package.json
Labels: dependencies, configuration, feature

#207 Feat/fieldlink adaptor
  package-lock.json
  package.json
Labels: dependencies, configuration, feature

#209 chore(release): 3.0.0-alpha.2
  package-lock.json
  package.json
Labels: dependencies, configuration

#210 build(deps): bumps knex and json5 versions
  package-lock.json
  package.json
Labels: dependencies, configuration, chore

#197 fix: adjust transaction on timer treatment of activity managers
  src/core/persist/knex.js
  src/core/workflow/activity_manager.js
Labels: bug, js

#212 chore(release): 2.18.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#211 build(deps): bumps knex and json5 versions
  README.md
  package-lock.json
  package.json
Labels: dependencies, configuration, doc, chore

#215 fix: adjust transaction handling on n 'interrupt activity manager' me…
  src/core/workflow/activity_manager.js
  src/core/workflow/process.js
Labels: bug, js

#216 chore(release): 2.18.3
  package-lock.json
  package.json
Labels: dependencies, configuration

#217 Chore/updates beta
  README.md
  src/core/workflow/activity_manager.js
  src/core/workflow/process.js
Labels: doc, js, chore

#218 chore(release): 2.19.0-beta.3
  package-lock.json
  package.json
Labels: dependencies, configuration

#220 fix: adjust payload on preProcessising of http node
  src/core/workflow/nodes/http.js
Labels: bug, js

#222 fix: adjust 'step number' transaction injection
  src/core/persist/knex/process.js
  src/core/workflow/process.js
Labels: bug, js

#223 chore(release): 2.19.0-beta.5
  package-lock.json
  package.json
Labels: dependencies, configuration

#214 Refactor input prepare()
  package-lock.json
  package.json
  src/core/utils/input.js
  src/core/utils/tests/unitary/input.test.js
Labels: dependencies, configuration, feature, js, test

#224 chore(release): 2.19.0-beta.6
  package-lock.json
  package.json
Labels: dependencies, configuration

#225 fix: adds transaction input on 'getLastStateByProcess' method
  src/core/persist/knex/process.js
  src/core/workflow/process.js
Labels: bug, js

#227 Fix/step number transaction
  src/core/persist/knex/process.js
  src/core/workflow/process.js
Labels: bug, js

#226 chore(release): 2.19.0-beta.7
  package-lock.json
  package.json
Labels: dependencies, configuration

#228 chore(release): 2.18.4
  package-lock.json
  package.json
Labels: dependencies, configuration
